server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: admin-service
  boot:
    admin:
      instance-auth:
        service-map:
          config-service:
            user-name: root
            user-password: s3cr3t