server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  security:
    oauth2:
      client:
        registration:
          spring-cloud-gateway-client:
            redirect-uri: http://localhost:8080/login/oauth2/code/gateway-service
            authorization-grant-type: authorization_code
            client-secret: 34AXv23Nxv9lmqErN5wrtsVleSYHarqN
            client-id: gateway-client
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/autoplants-realm
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**